### ISSUE TITLE
Implement feature icons in the info section

### ISSUE THREAD

**Issue by chicharr** [hlxsites/realmadrid#32]
The info section of the vip area is the section after the hero component. 
In some pages there are 3 icons shown, e.g. https://www.realmadrid.com/area-vip/partido-vip/silver-club-1anfiteatro

![Screenshot 2023-05-03 at 17 11 56](https://user-images.githubusercontent.com/43381734/235959962-1e4cefb3-f946-437d-96d4-d219b84e0a73.png)

![Screenshot 2023-05-03 at 17 12 18](https://user-images.githubusercontent.com/43381734/235960009-6b526e09-44bf-4b9c-92d1-76ed00119bae.png)

The first 2 icons "Atención personalizada" and "Catering Gourmet" open a popup with information when the user clicks on it. This can be implemented as a fragments.

The third one opens a popup with an iframe with the 360 view. The url of this iframe needs to be configured in the document itself.

**Comment by vdua** [comment]
There are two ways of implementing this

1.  as an enhancement to cards block (https://github.com/hlxsites/realmadrid/pull/36)
2. a new block that uses the cards block ([https:](https://github.com/hlxsites/realmadrid/pull/37)

Personally I like the second approach since it doesn't involve modifying the cards block (which is stable and can be reused in its current form). @chicharr Do you have any opinion on the same ?

**Comment by chicharr** [comment]
Hi @vdua 
I would use a dedicated block, extending the cards one. Similar to what you have implemented in your PR. 
With one remark:
the first 2 features have the same content wherever they are used, while the 3rd one embeds an iframe with a different url.
The second column of each card could be:
* text: as you have implemented so far
* path to a fragment: so authors don't need to write same content in all pages using it
* url of the iframe: as you implemented it

**Comment by vdua** [comment]
Also would need to load the iframe when it is clicked to ensure 100 LHS.
